#!/bin/sh

#
# rappture
#
/usr/bin/invoke_app "$@" -t aspectdesktop \
                         -e Aspect_DIR=/apps/share64/debian10/aspect/aspect-2.5.0pre \
                         -u aspect-2.5.0-pre \
                         -C rappture

#
# jupyter
#
#/usr/bin/invoke_app "$@" -t hubtooltemplatepublic \
#                         -C "start_jupyter -t -T @tool pc4nanobio.ipynb" \
#                         -u anaconda2-5.1
